title: <a href="https://www.bschool.cuhk.edu.hk/staff/huang-junfei/">Junfei Huang</a>
siteName: Junfei Huang | CUHK
position: Associate Professor
affiliation: Department of Decisions, Operations and Technology<br>CUHK Business School
email: <a href="mailto:junfeih@cuhk.edu.hk">junfeih@cuhk.edu.hk</a>
keywords: Junfei Huang's Homepage
google_scholar: #https://scholar.google.com/
github_link: #https://github.com/
linkedin: #https://www.linkedin.com/
avatar: https://www.bschool.cuhk.edu.hk/wp-content/uploads/Huang-Junfei_c.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Junfei Huang's Homepage
markdown: kramdown
canonical: https://hjfcuhk.github.io/
